from ubuntu:20.04
run apt-get update && \
  apt-get install -y \
    locales git curl wget build-essential libssl-dev libreadline-dev zlib1g-dev && \
  git clone --depth 1 https://github.com/rbenv/rbenv.git /root/.rbenv && \
  git clone --depth 1 https://github.com/rbenv/ruby-build.git /root/.rbenv/plugins/ruby-build && \
  echo "ja_JP UTF-8" > /etc/locale.gen && \
  locale-gen && \
  { \
    echo 'if [ -e $HOME/.rbenv ]; then'; \
    echo '  export PATH="$HOME/.rbenv/bin:$PATH"'; \
    echo '  eval "$(rbenv init -)"'; \
    echo 'fi'; \
    echo "alias ls='ls --color=auto'"; \
    echo "alias l='l=ls'"; \
    echo "alias ll='ls -alhF'"; \
    echo "export LANG='ja_JP.UTF-8'"; \
    echo 'export HISTCONTROL=erasedups:ignorebth'; \
    echo "export HISTIGNORE=''"; \
    echo 'export HISTSIZE=100'; \
    echo 'export HISTFILESIZE=1000'; \
    echo "export MAKEOPTS='-j8'"; \
    echo "export PS1='\\\[\\\e]0;\\\w\\\a\\\]\\\n\\\[\\\e[32m\\\]\\\u@\\\h \\\[\\\e[35m\\\]rbenv\\\[\\\e[0m\\\] \\\[\\\e[33m\\\]\\\w\\\[\\\e[0m\\\]\\\n\\\$ '"; \
    echo 'cd'; \
  } > /root/.bashrc
entrypoint ["/bin/bash"]
cmd []
